package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/nospy/albion-openradar/internal/photon"
)

func runInventory(in, outPath string) error {
	events := map[byte]int{}
	requests := map[byte]int{}
	responses := map[byte]int{}

	parser := photon.NewPhotonParser(
		func(e *photon.EventData) { events[e.Code]++ },
		func(r *photon.OperationRequest) { requests[r.OperationCode]++ },
		func(r *photon.OperationResponse) { responses[r.OperationCode]++ },
	)

	if err := iteratePcap(in, func(payload []byte) error {
		parser.ReceivePacket(payload)
		return nil
	}); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("# Protocol18 Observed Codes\n\n")
	sb.WriteString("Generated by `cmd/photon-dump --inventory`. One row per code, with count.\n\n")
	writeCensusSection(&sb, "Event codes", events)
	writeCensusSection(&sb, "Operation requests", requests)
	writeCensusSection(&sb, "Operation responses", responses)

	return os.WriteFile(outPath, []byte(sb.String()), 0o644)
}

func writeCensusSection(sb *strings.Builder, title string, m map[byte]int) {
	sb.WriteString("## " + title + "\n\n")
	sb.WriteString("| Code | Count |\n|---:|---:|\n")
	keys := make([]int, 0, len(m))
	for k := range m {
		keys = append(keys, int(k))
	}
	sort.Ints(keys)
	for _, k := range keys {
		sb.WriteString(fmt.Sprintf("| %d | %d |\n", k, m[byte(k)]))
	}
	sb.WriteString("\n")
}
