package main

import (
	"fmt"
	"maps"
	"os"
	"slices"
	"strings"

	"github.com/nospy/albion-openradar/internal/photon"
)

func runInventory(in, outPath string) error {
	// Albion event/op code lives in Parameters[252]/[253], not the Photon wire Code byte.
	events := map[int]int{}
	requests := map[int]int{}
	responses := map[int]int{}

	parser := photon.NewPhotonParser(
		func(e *photon.EventData) {
			photon.PostProcessEvent(e)
			events[intFromParam(e.Parameters[252])]++
		},
		func(r *photon.OperationRequest) {
			photon.PostProcessRequest(r)
			requests[intFromParam(r.Parameters[253])]++
		},
		func(r *photon.OperationResponse) {
			photon.PostProcessResponse(r)
			responses[intFromParam(r.Parameters[253])]++
		},
	)

	if err := iteratePcap(in, func(payload []byte) error {
		parser.ReceivePacket(payload)
		return nil
	}); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("# Protocol18 Observed Codes\n\n")
	sb.WriteString("Generated by `tools/photon-dump --inventory`. One row per code, with count.\n\n")
	writeCensusSection(&sb, "Event codes", events)
	writeCensusSection(&sb, "Operation requests", requests)
	writeCensusSection(&sb, "Operation responses", responses)

	return os.WriteFile(outPath, []byte(sb.String()), 0o644)
}

func writeCensusSection(sb *strings.Builder, title string, m map[int]int) {
	sb.WriteString("## " + title + "\n\n")
	sb.WriteString("| Code | Count |\n|---:|---:|\n")
	for _, k := range slices.Sorted(maps.Keys(m)) {
		fmt.Fprintf(sb, "| %d | %d |\n", k, m[k])
	}
	sb.WriteString("\n")
}

func intFromParam(v any) int {
	switch x := v.(type) {
	case byte:
		return int(x)
	case int8:
		return int(x)
	case int16:
		return int(x)
	case int32:
		return int(x)
	case int64:
		return int(x)
	}
	return -1
}
